name: "Feature Request"
description: "Suggest a feature or enhancement"
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:

- type: textarea
  attributes:
  label: "Feature description"
  description: "What do you want to happen?"
  validations:
  required: true

- type: textarea
  attributes:
  label: "Motivation"
  description: "Why is this feature useful? What problem does it solve?"
  validations:
  required: true

- type: textarea
  attributes:
  label: "Proposed solution"
  description: "How should it work? Any example code or UI suggestions?"
